Test:
- src/test/*

Documentation:
- ./*.md
- ./**/*.md

Configuration:
- .github/*.yml
- .github/*.yaml
- .github/**/*.yml
- .github/**/*.yaml
- .github/workflow/*
- ./**/*.yml
- ./**/*.yaml
- ./**/*.json
- ./**/*.xml
- .gitignore
- config.json


Git:
- .github/*
- .gitignore
