name: "Greet Newcomers"

on: [issues,pull_request]

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hey there! Thanks for Contributing! Please take the time until I have a look to check whether the appropriate labels are set!'
        pr-message: 'Thank you for Contributing! Take the time until I check your appreciated Pull Request to see if any labels are missing and watch the pipeline :) '